### ISSUE TITLE
Client_id

### ISSUE THREAD

**Issue by dagro105** [ingwinlu/python-twitch#26]
Hi guys,

I'm starting to use the Twitch Api to check out some statistic stuff. How do I put my client_id into that program? Do I need to give it via the url-query (...?&client_id=...) or is there a smoother way to send my client_id to each query? (I'm still a beginner in programming so pls don't be so hard!

**Comment by ingwinlu** [comment]
If you want to use python-twitch you can NOT use a client_id yet. As it is not implemented.

**Comment by martinjuhasz** [comment]
is this still true?

**Comment by ingwinlu** [comment]
yes as I have not yet gotten around to it even though it is required now, see #29

**Comment by ingwinlu** [comment]
client id can now be provided, let me know if you need anything else or if it isn't working for you as expected.
