### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'README.rst'

### ISSUE THREAD

**Issue by DNNYVST** [ingwinlu/python-twitch#6]
Trying to pip install.
![image](https://cloud.githubusercontent.com/assets/7424992/6475731/876db482-c1db-11e4-8b27-19bbbcafcb50.png)

**Comment by ingwinlu** [comment]
Hey, i recently moved the readme from an md file to rst to be compatible with pypy. Forgot updating the manifest file.

#thanks for reporting, should work now
